package com.xiaohoo.api.domain;

public class ActivityPaymentKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_payment.activity_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_payment.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_payment.activity_id
     *
     * @return the value of activity_payment.activity_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_payment.activity_id
     *
     * @param activityId the value for activity_payment.activity_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_payment.id
     *
     * @return the value of activity_payment.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_payment.id
     *
     * @param id the value for activity_payment.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }
}