package com.xiaohoo.api.domain;

import java.util.Date;

public class Advertisement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.title
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.image
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.effective_from
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Date effectiveFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.effective_to
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Date effectiveTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.id
     *
     * @return the value of advertisement.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.id
     *
     * @param id the value for advertisement.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.title
     *
     * @return the value of advertisement.title
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.title
     *
     * @param title the value for advertisement.title
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.image
     *
     * @return the value of advertisement.image
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.image
     *
     * @param image the value for advertisement.image
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.effective_from
     *
     * @return the value of advertisement.effective_from
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Date getEffectiveFrom() {
        return effectiveFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.effective_from
     *
     * @param effectiveFrom the value for advertisement.effective_from
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setEffectiveFrom(Date effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.effective_to
     *
     * @return the value of advertisement.effective_to
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Date getEffectiveTo() {
        return effectiveTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.effective_to
     *
     * @param effectiveTo the value for advertisement.effective_to
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setEffectiveTo(Date effectiveTo) {
        this.effectiveTo = effectiveTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.create_time
     *
     * @return the value of advertisement.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.create_time
     *
     * @param createTime the value for advertisement.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.update_time
     *
     * @return the value of advertisement.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.update_time
     *
     * @param updateTime the value for advertisement.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}