package com.xiaohoo.api.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Charge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.charge_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String chargeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.subject
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.channel
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.body
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.clientip
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String clientip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.amount
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.currency
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.message
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.address
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.product_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.orderno
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.created
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.paid
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String paid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.refunded
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String refunded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.appid
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.timeexpire
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String timeexpire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.description
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.id
     *
     * @return the value of charge.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.id
     *
     * @param id the value for charge.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.charge_id
     *
     * @return the value of charge.charge_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getChargeId() {
        return chargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.charge_id
     *
     * @param chargeId the value for charge.charge_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setChargeId(String chargeId) {
        this.chargeId = chargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.subject
     *
     * @return the value of charge.subject
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.subject
     *
     * @param subject the value for charge.subject
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.channel
     *
     * @return the value of charge.channel
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.channel
     *
     * @param channel the value for charge.channel
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.body
     *
     * @return the value of charge.body
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.body
     *
     * @param body the value for charge.body
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.clientip
     *
     * @return the value of charge.clientip
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getClientip() {
        return clientip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.clientip
     *
     * @param clientip the value for charge.clientip
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setClientip(String clientip) {
        this.clientip = clientip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.amount
     *
     * @return the value of charge.amount
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.amount
     *
     * @param amount the value for charge.amount
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.currency
     *
     * @return the value of charge.currency
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.currency
     *
     * @param currency the value for charge.currency
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.message
     *
     * @return the value of charge.message
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.message
     *
     * @param message the value for charge.message
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.address
     *
     * @return the value of charge.address
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.address
     *
     * @param address the value for charge.address
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.product_id
     *
     * @return the value of charge.product_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.product_id
     *
     * @param productId the value for charge.product_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.orderno
     *
     * @return the value of charge.orderno
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.orderno
     *
     * @param orderno the value for charge.orderno
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.created
     *
     * @return the value of charge.created
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.created
     *
     * @param created the value for charge.created
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setCreated(String created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.paid
     *
     * @return the value of charge.paid
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getPaid() {
        return paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.paid
     *
     * @param paid the value for charge.paid
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setPaid(String paid) {
        this.paid = paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.refunded
     *
     * @return the value of charge.refunded
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getRefunded() {
        return refunded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.refunded
     *
     * @param refunded the value for charge.refunded
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setRefunded(String refunded) {
        this.refunded = refunded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.appid
     *
     * @return the value of charge.appid
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.appid
     *
     * @param appid the value for charge.appid
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.timeexpire
     *
     * @return the value of charge.timeexpire
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getTimeexpire() {
        return timeexpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.timeexpire
     *
     * @param timeexpire the value for charge.timeexpire
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setTimeexpire(String timeexpire) {
        this.timeexpire = timeexpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.description
     *
     * @return the value of charge.description
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.description
     *
     * @param description the value for charge.description
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.create_time
     *
     * @return the value of charge.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.create_time
     *
     * @param createTime the value for charge.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.update_time
     *
     * @return the value of charge.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.update_time
     *
     * @param updateTime the value for charge.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}