package com.xiaohoo.api.domain;

import java.util.Date;

public class GroupMomentThumbUp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_moment_thumb_up.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_moment_thumb_up.group_moments_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer groupMomentsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_moment_thumb_up.thumb_up_by
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer thumbUpBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_moment_thumb_up.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_moment_thumb_up.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_moment_thumb_up.id
     *
     * @return the value of group_moment_thumb_up.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_moment_thumb_up.id
     *
     * @param id the value for group_moment_thumb_up.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_moment_thumb_up.group_moments_id
     *
     * @return the value of group_moment_thumb_up.group_moments_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getGroupMomentsId() {
        return groupMomentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_moment_thumb_up.group_moments_id
     *
     * @param groupMomentsId the value for group_moment_thumb_up.group_moments_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setGroupMomentsId(Integer groupMomentsId) {
        this.groupMomentsId = groupMomentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_moment_thumb_up.thumb_up_by
     *
     * @return the value of group_moment_thumb_up.thumb_up_by
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getThumbUpBy() {
        return thumbUpBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_moment_thumb_up.thumb_up_by
     *
     * @param thumbUpBy the value for group_moment_thumb_up.thumb_up_by
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setThumbUpBy(Integer thumbUpBy) {
        this.thumbUpBy = thumbUpBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_moment_thumb_up.create_time
     *
     * @return the value of group_moment_thumb_up.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_moment_thumb_up.create_time
     *
     * @param createTime the value for group_moment_thumb_up.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_moment_thumb_up.update_time
     *
     * @return the value of group_moment_thumb_up.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_moment_thumb_up.update_time
     *
     * @param updateTime the value for group_moment_thumb_up.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}