package com.xiaohoo.api.domain;

public class GroupMembersKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.group_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_members.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.group_id
     *
     * @return the value of group_members.group_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.group_id
     *
     * @param groupId the value for group_members.group_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_members.id
     *
     * @return the value of group_members.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_members.id
     *
     * @param id the value for group_members.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }
}