package com.xiaohoo.api.domain;

import java.util.Date;

public class MomentResponse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_response.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_response.moments_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer momentsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_response.content
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_response.response_by
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer responseBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_response.response_to
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer responseTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_response.read
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Boolean read;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_response.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_response.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_response.id
     *
     * @return the value of moment_response.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_response.id
     *
     * @param id the value for moment_response.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_response.moments_id
     *
     * @return the value of moment_response.moments_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getMomentsId() {
        return momentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_response.moments_id
     *
     * @param momentsId the value for moment_response.moments_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setMomentsId(Integer momentsId) {
        this.momentsId = momentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_response.content
     *
     * @return the value of moment_response.content
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_response.content
     *
     * @param content the value for moment_response.content
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_response.response_by
     *
     * @return the value of moment_response.response_by
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getResponseBy() {
        return responseBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_response.response_by
     *
     * @param responseBy the value for moment_response.response_by
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setResponseBy(Integer responseBy) {
        this.responseBy = responseBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_response.response_to
     *
     * @return the value of moment_response.response_to
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getResponseTo() {
        return responseTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_response.response_to
     *
     * @param responseTo the value for moment_response.response_to
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setResponseTo(Integer responseTo) {
        this.responseTo = responseTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_response.read
     *
     * @return the value of moment_response.read
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Boolean getRead() {
        return read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_response.read
     *
     * @param read the value for moment_response.read
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setRead(Boolean read) {
        this.read = read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_response.create_time
     *
     * @return the value of moment_response.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_response.create_time
     *
     * @param createTime the value for moment_response.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_response.update_time
     *
     * @return the value of moment_response.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_response.update_time
     *
     * @param updateTime the value for moment_response.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}