package com.xiaohoo.api.domain;

import java.util.Date;

public class UserAdvise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_advise.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_advise.user_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_advise.content
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_advise.category
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_advise.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_advise.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_advise.id
     *
     * @return the value of user_advise.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_advise.id
     *
     * @param id the value for user_advise.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_advise.user_id
     *
     * @return the value of user_advise.user_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_advise.user_id
     *
     * @param userId the value for user_advise.user_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_advise.content
     *
     * @return the value of user_advise.content
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_advise.content
     *
     * @param content the value for user_advise.content
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_advise.category
     *
     * @return the value of user_advise.category
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_advise.category
     *
     * @param category the value for user_advise.category
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_advise.create_time
     *
     * @return the value of user_advise.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_advise.create_time
     *
     * @param createTime the value for user_advise.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_advise.update_time
     *
     * @return the value of user_advise.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_advise.update_time
     *
     * @param updateTime the value for user_advise.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}