package com.xiaohoo.api.domain;

import java.util.Date;

public class User {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.id
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.phone
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.nickname
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String nickname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.password
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.icon_path
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String iconPath;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.sex
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private Integer sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.birthday
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private Date birthday;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.school_id
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private Integer schoolId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.school_name
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String schoolName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.collage_id
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private Integer collageId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.collage_name
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String collageName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.major_id
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private Integer majorId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.major_name
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String majorName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.education
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String education;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.education_date
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private Date educationDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.address
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.province
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String province;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.city
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String city;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.street
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String street;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.postcode
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String postcode;

	/**
	 * 权限：0-9（手机用户权限），10-（后台用户权限）<br>
	 * 0为普通用户<br>
	 * 1学生社用户，已通过审批，可开通社群<br>
	 * 10后台管理用户（可登陆后台）<br>
	 * 
	 */
	private Integer level;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.accesstoken
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String accesstoken;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.openid
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String openid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.vip_expire_time
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private Date vipExpireTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.cid
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String cid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.user_dsp_name
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String userDspName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.email
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.status
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.invite_code
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String inviteCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.my_invite_code
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String myInviteCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.registermode
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private Integer registermode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.district
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private String district;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.create_time
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.update_time
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.id
	 *
	 * @return the value of user.id
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.id
	 *
	 * @param id
	 *            the value for user.id
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.phone
	 *
	 * @return the value of user.phone
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.phone
	 *
	 * @param phone
	 *            the value for user.phone
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.nickname
	 *
	 * @return the value of user.nickname
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.nickname
	 *
	 * @param nickname
	 *            the value for user.nickname
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.password
	 *
	 * @return the value of user.password
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.password
	 *
	 * @param password
	 *            the value for user.password
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.icon_path
	 *
	 * @return the value of user.icon_path
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getIconPath() {
		return iconPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.icon_path
	 *
	 * @param iconPath
	 *            the value for user.icon_path
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setIconPath(String iconPath) {
		this.iconPath = iconPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.sex
	 *
	 * @return the value of user.sex
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.sex
	 *
	 * @param sex
	 *            the value for user.sex
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.birthday
	 *
	 * @return the value of user.birthday
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.birthday
	 *
	 * @param birthday
	 *            the value for user.birthday
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.school_id
	 *
	 * @return the value of user.school_id
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public Integer getSchoolId() {
		return schoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.school_id
	 *
	 * @param schoolId
	 *            the value for user.school_id
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.school_name
	 *
	 * @return the value of user.school_name
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getSchoolName() {
		return schoolName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.school_name
	 *
	 * @param schoolName
	 *            the value for user.school_name
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.collage_id
	 *
	 * @return the value of user.collage_id
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public Integer getCollageId() {
		return collageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.collage_id
	 *
	 * @param collageId
	 *            the value for user.collage_id
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setCollageId(Integer collageId) {
		this.collageId = collageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.collage_name
	 *
	 * @return the value of user.collage_name
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getCollageName() {
		return collageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.collage_name
	 *
	 * @param collageName
	 *            the value for user.collage_name
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setCollageName(String collageName) {
		this.collageName = collageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.major_id
	 *
	 * @return the value of user.major_id
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public Integer getMajorId() {
		return majorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.major_id
	 *
	 * @param majorId
	 *            the value for user.major_id
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setMajorId(Integer majorId) {
		this.majorId = majorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.major_name
	 *
	 * @return the value of user.major_name
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getMajorName() {
		return majorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.major_name
	 *
	 * @param majorName
	 *            the value for user.major_name
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setMajorName(String majorName) {
		this.majorName = majorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.education
	 *
	 * @return the value of user.education
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getEducation() {
		return education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.education
	 *
	 * @param education
	 *            the value for user.education
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setEducation(String education) {
		this.education = education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.education_date
	 *
	 * @return the value of user.education_date
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public Date getEducationDate() {
		return educationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.education_date
	 *
	 * @param educationDate
	 *            the value for user.education_date
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setEducationDate(Date educationDate) {
		this.educationDate = educationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.address
	 *
	 * @return the value of user.address
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.address
	 *
	 * @param address
	 *            the value for user.address
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.province
	 *
	 * @return the value of user.province
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.province
	 *
	 * @param province
	 *            the value for user.province
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.city
	 *
	 * @return the value of user.city
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.city
	 *
	 * @param city
	 *            the value for user.city
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.street
	 *
	 * @return the value of user.street
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getStreet() {
		return street;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.street
	 *
	 * @param street
	 *            the value for user.street
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setStreet(String street) {
		this.street = street;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.postcode
	 *
	 * @return the value of user.postcode
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getPostcode() {
		return postcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.postcode
	 *
	 * @param postcode
	 *            the value for user.postcode
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.level
	 *
	 * @return the value of user.level
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.level
	 *
	 * @param level
	 *            the value for user.level
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.accesstoken
	 *
	 * @return the value of user.accesstoken
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getAccesstoken() {
		return accesstoken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.accesstoken
	 *
	 * @param accesstoken
	 *            the value for user.accesstoken
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setAccesstoken(String accesstoken) {
		this.accesstoken = accesstoken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.openid
	 *
	 * @return the value of user.openid
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.openid
	 *
	 * @param openid
	 *            the value for user.openid
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.vip_expire_time
	 *
	 * @return the value of user.vip_expire_time
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public Date getVipExpireTime() {
		return vipExpireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.vip_expire_time
	 *
	 * @param vipExpireTime
	 *            the value for user.vip_expire_time
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setVipExpireTime(Date vipExpireTime) {
		this.vipExpireTime = vipExpireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.cid
	 *
	 * @return the value of user.cid
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.cid
	 *
	 * @param cid
	 *            the value for user.cid
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setCid(String cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.user_dsp_name
	 *
	 * @return the value of user.user_dsp_name
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getUserDspName() {
		return userDspName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.user_dsp_name
	 *
	 * @param userDspName
	 *            the value for user.user_dsp_name
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setUserDspName(String userDspName) {
		this.userDspName = userDspName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.email
	 *
	 * @return the value of user.email
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.email
	 *
	 * @param email
	 *            the value for user.email
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.status
	 *
	 * @return the value of user.status
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.status
	 *
	 * @param status
	 *            the value for user.status
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.invite_code
	 *
	 * @return the value of user.invite_code
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getInviteCode() {
		return inviteCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.invite_code
	 *
	 * @param inviteCode
	 *            the value for user.invite_code
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setInviteCode(String inviteCode) {
		this.inviteCode = inviteCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.my_invite_code
	 *
	 * @return the value of user.my_invite_code
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getMyInviteCode() {
		return myInviteCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.my_invite_code
	 *
	 * @param myInviteCode
	 *            the value for user.my_invite_code
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setMyInviteCode(String myInviteCode) {
		this.myInviteCode = myInviteCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.registermode
	 *
	 * @return the value of user.registermode
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public Integer getRegistermode() {
		return registermode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.registermode
	 *
	 * @param registermode
	 *            the value for user.registermode
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setRegistermode(Integer registermode) {
		this.registermode = registermode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.district
	 *
	 * @return the value of user.district
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public String getDistrict() {
		return district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.district
	 *
	 * @param district
	 *            the value for user.district
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setDistrict(String district) {
		this.district = district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.create_time
	 *
	 * @return the value of user.create_time
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.create_time
	 *
	 * @param createTime
	 *            the value for user.create_time
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.update_time
	 *
	 * @return the value of user.update_time
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.update_time
	 *
	 * @param updateTime
	 *            the value for user.update_time
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}