package com.xiaohoo.api.domain;

import java.util.Date;

public class UserFocus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus.user_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus.focus_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Integer focusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus.focus_name
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private String focusName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus.id
     *
     * @return the value of user_focus.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus.id
     *
     * @param id the value for user_focus.id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus.user_id
     *
     * @return the value of user_focus.user_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus.user_id
     *
     * @param userId the value for user_focus.user_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus.focus_id
     *
     * @return the value of user_focus.focus_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Integer getFocusId() {
        return focusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus.focus_id
     *
     * @param focusId the value for user_focus.focus_id
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setFocusId(Integer focusId) {
        this.focusId = focusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus.focus_name
     *
     * @return the value of user_focus.focus_name
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public String getFocusName() {
        return focusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus.focus_name
     *
     * @param focusName the value for user_focus.focus_name
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setFocusName(String focusName) {
        this.focusName = focusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus.create_time
     *
     * @return the value of user_focus.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus.create_time
     *
     * @param createTime the value for user_focus.create_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus.update_time
     *
     * @return the value of user_focus.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus.update_time
     *
     * @param updateTime the value for user_focus.update_time
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}