package com.xiaohoo.api.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.xiaohoo.api.domain.Activity;
import com.xiaohoo.api.domain.ActivityExample;
import com.xiaohoo.api.domain.request.ActivitySearchRequest;

public interface ActivityMapper {

	/**
	 * 用户已参加活动列表
	 * 
	 * @return
	 */
	List<Activity> getUserActivities(@Param("userId") Integer userId,
			@Param("start") Integer start, @Param("count") Integer count);

	/**
	 * 用户收藏活动列表
	 * 
	 * @param userId
	 * @param start
	 * @param count
	 * @return
	 */
	List<Activity> getUserCollectActivites(@Param("userId") Integer userId,
			@Param("start") Integer start, @Param("count") Integer count);

	List<Activity> getActivitiesByType(Map<String, Object> map);

	List<Activity> searchActivities(
			@Param("search") ActivitySearchRequest search);

	/**
	 * 用户半小时没付钱，活动参与人数减1
	 * 
	 * @param activityId
	 * @return
	 */
	int updateInNumberMinusOne(@Param("activityId") Integer activityId);

	/**
	 * 获得活动剩余人数
	 * 
	 * @param activityId
	 * @return
	 */
	int getLeftNumberByActivityId(Integer activityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int countByExample(ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int deleteByExample(ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int insert(Activity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int insertSelective(Activity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	List<Activity> selectByExample(ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	Activity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Activity record,
			@Param("example") ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByExample(@Param("record") Activity record,
			@Param("example") ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByPrimaryKeySelective(Activity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByPrimaryKey(Activity record);

}