package com.xiaohoo.api.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.xiaohoo.api.domain.ActivityIn;
import com.xiaohoo.api.domain.ActivityInExample;
import com.xiaohoo.api.domain.ActivityInKey;

public interface ActivityInMapper {

	int updateStatusByActivityId(@Param("status") String status,
			@Param("userId") Integer userId,
			@Param("activityId") Integer activityId);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_in
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int countByExample(ActivityInExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_in
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int deleteByExample(ActivityInExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_in
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int deleteByPrimaryKey(ActivityInKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_in
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int insert(ActivityIn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_in
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int insertSelective(ActivityIn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_in
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	List<ActivityIn> selectByExample(ActivityInExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_in
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	ActivityIn selectByPrimaryKey(ActivityInKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_in
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ActivityIn record,
			@Param("example") ActivityInExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_in
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByExample(@Param("record") ActivityIn record,
			@Param("example") ActivityInExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_in
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByPrimaryKeySelective(ActivityIn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_in
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByPrimaryKey(ActivityIn record);
}