package com.xiaohoo.api.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.xiaohoo.api.domain.ActivityPayment;
import com.xiaohoo.api.domain.ActivityPaymentExample;
import com.xiaohoo.api.domain.ActivityPaymentKey;

public interface ActivityPaymentMapper {

	List<ActivityPayment> getByActivityId(Integer activityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_payment
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int countByExample(ActivityPaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_payment
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int deleteByExample(ActivityPaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_payment
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int deleteByPrimaryKey(ActivityPaymentKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_payment
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int insert(ActivityPayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_payment
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int insertSelective(ActivityPayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_payment
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	List<ActivityPayment> selectByExample(ActivityPaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_payment
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	ActivityPayment selectByPrimaryKey(ActivityPaymentKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_payment
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ActivityPayment record,
			@Param("example") ActivityPaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_payment
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByExample(@Param("record") ActivityPayment record,
			@Param("example") ActivityPaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_payment
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByPrimaryKeySelective(ActivityPayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table activity_payment
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByPrimaryKey(ActivityPayment record);
}