package com.xiaohoo.api.dao;

import com.xiaohoo.api.domain.Favorites;
import com.xiaohoo.api.domain.FavoritesExample;
import com.xiaohoo.api.domain.FavoritesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FavoritesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int countByExample(FavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int deleteByExample(FavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int deleteByPrimaryKey(FavoritesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int insert(Favorites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int insertSelective(Favorites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    List<Favorites> selectByExample(FavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    Favorites selectByPrimaryKey(FavoritesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") Favorites record, @Param("example") FavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByExample(@Param("record") Favorites record, @Param("example") FavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByPrimaryKeySelective(Favorites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByPrimaryKey(Favorites record);
}