package com.xiaohoo.api.dao;

import com.xiaohoo.api.domain.GroupMomentScroe;
import com.xiaohoo.api.domain.GroupMomentScroeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupMomentScroeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_scroe
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int countByExample(GroupMomentScroeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_scroe
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int deleteByExample(GroupMomentScroeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_scroe
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_scroe
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int insert(GroupMomentScroe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_scroe
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int insertSelective(GroupMomentScroe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_scroe
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    List<GroupMomentScroe> selectByExample(GroupMomentScroeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_scroe
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    GroupMomentScroe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_scroe
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") GroupMomentScroe record, @Param("example") GroupMomentScroeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_scroe
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByExample(@Param("record") GroupMomentScroe record, @Param("example") GroupMomentScroeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_scroe
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByPrimaryKeySelective(GroupMomentScroe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_scroe
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByPrimaryKey(GroupMomentScroe record);
}