package com.xiaohoo.api.dao;

import com.xiaohoo.api.domain.GroupMomentResponse;
import com.xiaohoo.api.domain.GroupMomentResponseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupMomentResponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_response
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int countByExample(GroupMomentResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_response
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int deleteByExample(GroupMomentResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_response
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_response
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int insert(GroupMomentResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_response
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int insertSelective(GroupMomentResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_response
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    List<GroupMomentResponse> selectByExample(GroupMomentResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_response
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    GroupMomentResponse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_response
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") GroupMomentResponse record, @Param("example") GroupMomentResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_response
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByExample(@Param("record") GroupMomentResponse record, @Param("example") GroupMomentResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_response
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByPrimaryKeySelective(GroupMomentResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_moment_response
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByPrimaryKey(GroupMomentResponse record);
    
    /**
     * 此方法用于查看该条状态的所有回复信息
     * 倪永烽代码
     */
    
    List<GroupMomentResponse> selectByGroupMomentsId(Integer groupMomentsId);
}