package com.xiaohoo.api.dao;

import com.xiaohoo.api.domain.Moments;
import com.xiaohoo.api.domain.MomentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MomentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moments
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int countByExample(MomentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moments
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int deleteByExample(MomentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moments
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moments
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int insert(Moments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moments
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int insertSelective(Moments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moments
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    List<Moments> selectByExample(MomentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moments
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    Moments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moments
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") Moments record, @Param("example") MomentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moments
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByExample(@Param("record") Moments record, @Param("example") MomentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moments
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByPrimaryKeySelective(Moments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moments
     *
     * @mbggenerated Thu May 04 20:51:39 CST 2017
     */
    int updateByPrimaryKey(Moments record);
}