package com.xiaohoo.api.dao;

import com.xiaohoo.api.domain.UserApplication;
import com.xiaohoo.api.domain.UserApplicationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserApplicationMapper {

	int updateStatusByUserId(@Param("userId") Integer userId,
			@Param("status") String status, @Param("comments") String comments);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_application
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int countByExample(UserApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_application
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int deleteByExample(UserApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_application
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_application
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int insert(UserApplication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_application
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int insertSelective(UserApplication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_application
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	List<UserApplication> selectByExample(UserApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_application
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	UserApplication selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_application
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByExampleSelective(@Param("record") UserApplication record,
			@Param("example") UserApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_application
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByExample(@Param("record") UserApplication record,
			@Param("example") UserApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_application
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByPrimaryKeySelective(UserApplication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_application
	 *
	 * @mbggenerated Thu May 04 20:51:39 CST 2017
	 */
	int updateByPrimaryKey(UserApplication record);
}