/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-04-16 08:32:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class man志愿者活动_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <title>Bootstrap Admin</title>\n");
      out.write("    <meta content=\"IE=edge,chrome=1\" http-equiv=\"X-UA-Compatible\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"lib/bootstrap/css/bootstrap.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"lib/bootstrap/css/bootstrap-responsive.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"stylesheets/theme.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"lib/font-awesome/css/font-awesome.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"stylesheets/panigate.css\">\n");
      out.write("\t<script src=\"lib/jquery-1.8.1.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"javascripts/panigate.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"javascripts/volunteerActivity.js\"></script>\n");
      out.write("    <!-- Demo page code -->\n");
      out.write("\n");
      out.write("    <style type=\"text/css\">\n");
      out.write("        #line-chart {\n");
      out.write("            height:300px;\n");
      out.write("            width:800px;\n");
      out.write("            margin: 0px auto;\n");
      out.write("            margin-top: 1em;\n");
      out.write("        }\n");
      out.write("        .brand { font-family: georgia, serif; }\n");
      out.write("        .brand .first {\n");
      out.write("            color: #ccc;\n");
      out.write("            font-style: italic;\n");
      out.write("        }\n");
      out.write("        .brand .second {\n");
      out.write("            color: #fff;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("      <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("    <!-- Le fav and touch icons -->\n");
      out.write("    <link rel=\"shortcut icon\" href=\"../assets/ico/favicon.ico\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"../assets/ico/apple-touch-icon-144-precomposed.png\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"../assets/ico/apple-touch-icon-114-precomposed.png\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"../assets/ico/apple-touch-icon-72-precomposed.png\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"../assets/ico/apple-touch-icon-57-precomposed.png\">\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("  <!--[if lt IE 7 ]> <body class=\"ie ie6\"> <![endif]-->\n");
      out.write("  <!--[if IE 7 ]> <body class=\"ie ie7\"> <![endif]-->\n");
      out.write("  <!--[if IE 8 ]> <body class=\"ie ie8\"> <![endif]-->\n");
      out.write("  <!--[if IE 9 ]> <body class=\"ie ie9\"> <![endif]-->\n");
      out.write("  <!--[if (gt IE 9)|!(IE)]><!-->\n");
      out.write("  <body>\n");
      out.write("  <!--<![endif]-->\n");
      out.write("\n");
      out.write("    <div class=\"navbar\">\n");
      out.write("        <div class=\"navbar-inner\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <ul class=\"nav pull-right\">\n");
      out.write("\n");
      out.write("                    <li id=\"fat-menu\" class=\"dropdown\">\n");
      out.write("                        <a href=\"#\" id=\"drop3\" role=\"button\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("                            <i class=\"icon-user\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                            <i class=\"icon-caret-down\"></i>\n");
      out.write("                        </a>\n");
      out.write("\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                            <!-- <li><a tabindex=\"-1\" href=\"#\">Settings</a></li> -->\n");
      out.write("                            <!-- <li class=\"divider\"></li> -->\n");
      out.write("                            <li><a tabindex=\"-1\" href=\"sign-in.html\">注销</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                </ul>\n");
      out.write("                <a class=\"brand\" href=\"manageIndex.jsp\"><span class=\"first\">浙江传媒学院</span> <span class=\"second\">第二课堂管理系统</span></a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("        <div class=\"row-fluid\">\n");
      out.write("            <div class=\"span3\">\n");
      out.write("                <div class=\"sidebar-nav\">\n");
      out.write("                  <div class=\"nav-header\" data-toggle=\"collapse\" data-target=\"#dashboard-menu\"><i class=\"icon-dashboard\"></i>导航栏</div>\n");
      out.write("                    <ul id=\"dashboard-menu\" class=\"nav nav-list collapse in\">\n");
      out.write("                      <li ><a href=\"manageIndex.jsp\">主页</a></li>\n");
      out.write("                      <li class=\"active\"><a href=\"man志愿者活动.jsp\">志愿者活动</a></li>\n");
      out.write("                      <li ><a href=\"man竞赛活动.jsp\">竞赛活动</a></li>\n");
      out.write("                      <li ><a href=\"man讲座.jsp\">讲座</a></li>\n");
      out.write("                      <li ><a href=\"man教师项目.jsp\">教师项目</a></li>\n");
      out.write("                      <li ><a href=\"manhelp.jsp\">帮助</a></li>\n");
      out.write("\n");
      out.write("                    </ul>\n");
      out.write("                <div class=\"nav-header\" data-toggle=\"collapse\" data-target=\"#accounts-menu\"><i class=\"icon-briefcase\"></i>第二课堂项目管理</span></div>\n");
      out.write("                <ul id=\"accounts-menu\" class=\"nav nav-list collapse in\">\n");
      out.write("                  <li ><a href=\"man志愿者活动发布.jsp\">志愿者活动管理</a></li>\n");
      out.write("                  <li ><a href=\"man竞赛活动发布.jsp\">竞赛活动管理</a></li>\n");
      out.write("                  <li ><a href=\"man讲座发布.jsp\">讲座管理</a></li>\n");
      out.write("                  <li ><a href=\"man教师项目发布.jsp\">教师项目管理</a></li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"nav-header\" data-toggle=\"collapse\" data-target=\"#legal-menu\"><i class=\"icon-legal\"></i>用户管理</div>\n");
      out.write("                <ul id=\"legal-menu\" class=\"nav nav-list collapse in\">\n");
      out.write("                  <li ><a href=\"manadd.jsp\">用户添加</a></li>\n");
      out.write("                  <li ><a href=\"mandelete.jsp\">用户删除</a></li>\n");
      out.write("                  <li ><a href=\"manupdate.jsp\">用户修改</a></li>\n");
      out.write("                  <li ><a href=\"manselect.jsp\">用户查看</a></li>\n");
      out.write("                </ul>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"span9\">\n");
      out.write("            <script type=\"text/javascript\" src=\"lib/jqplot/jquery.jqplot.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\" src=\"javascripts/graphDemo.js\"></script>\n");
      out.write("  <h1 class=\"page-title\">志愿者活动</h1>\n");
      out.write("<div class=\"well\">\n");
      out.write("  <table class=\"table\">\n");
      out.write("    <thead>\n");
      out.write("      <tr title=\"\" id=\"volunteerActivityList\">\n");
      out.write("        <th>#</th>\n");
      out.write("        <th>活动时间</th>\n");
      out.write("        <th>具体内容</th>\n");
      out.write("        <th>需要人数</th>\n");
      out.write("        <th>地点</th>\n");
      out.write("        <th>发布时间</th>\n");
      out.write("        <!-- <th style=\"width: 26px;\"></th> -->\n");
      out.write("      </tr>\n");
      out.write("      <!-- <tr>\n");
      out.write("        <th>1</th>\n");
      out.write("        <th>2017.05.06</th>\n");
      out.write("        <th>扫地</th>\n");
      out.write("        <th>5</th>\n");
      out.write("        <th>浙江传媒学院</th>\n");
      out.write("        <th>2017.04.12</th>\n");
      out.write("        <td>\n");
      out.write("            <a href=\"man志愿者活动发布.html\"><i class=\"icon-pencil\"></i></a>\n");
      out.write("            <a href=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i class=\"icon-remove\"></i></a>\n");
      out.write("        </td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <th>2</th>\n");
      out.write("        <th>2017.05.09</th>\n");
      out.write("        <th>拖地</th>\n");
      out.write("        <th>5</th>\n");
      out.write("        <th>浙江传媒学院</th>\n");
      out.write("        <th>2017.04.12</th>\n");
      out.write("        <td>\n");
      out.write("            <a href=\"man志愿者活动发布.html\"><i class=\"icon-pencil\"></i></a>\n");
      out.write("            <a href=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i class=\"icon-remove\"></i></a>\n");
      out.write("        </td>\n");
      out.write("      </tr> -->\n");
      out.write("    </thead>\n");
      out.write("    </table>\n");
      out.write("    <div id=\"Pagination\" class=\"right flickr\"></div>\n");
      out.write("</div>\n");
      out.write("<div class=\"well search-well\">\n");
      out.write("              <form class=\"form-inline\">\n");
      out.write("                  <input class=\"input-xlarge\" placeholder=\"Search Help...\" id=\"appendedInputButton\" type=\"text\">\n");
      out.write("                  <button class=\"btn\" type=\"button\"><i class=\"icon-search\"></i>Go</button>\n");
      out.write("              </form>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Le javascript\n");
      out.write("    ================================================== -->\n");
      out.write("    <!-- Placed at the end of the document so the pages load faster -->\n");
      out.write("    <script src=\"lib/bootstrap/js/bootstrap.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
